"use client";

import { useState } from "react";
import { ZikLogoMark } from "@/components/zik-logo";
import { allocationHistory, calculateAllocation, demoNetwork, demoProducts, money, percent, reportingWindows, simulateAllocation } from "@/lib/demo/affiliate-dashboard";
import s from "./dashboard.module.css";

const latest = calculateAllocation(demoNetwork.grossRevenue, demoNetwork.affiliateWeight, demoNetwork.totalWeight);
export function AffiliateDashboardDemo() {
  const [additional, setAdditional] = useState(0);
  const [gross, setGross] = useState<number>(demoNetwork.grossRevenue);
  const simulation = simulateAllocation(gross, additional);
  return <div className={`zk-surface ${s.page}`}>
    <a className={s.skip} href="#dashboard-main" data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-1" : undefined}>Skip to dashboard</a>
    <header className={s.header}><a href="/home" className={s.brand}><ZikLogoMark className={s.logo} /><span data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-2" : undefined}>Zik Pass <small>Affiliate programme</small></span></a><span className={s.badge} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-3" : undefined}>Demo — illustrative data</span></header>
    <main id="dashboard-main" className={s.main}>
      <div className={s.intro}><div><p className={s.eyebrow} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-4" : undefined}>PARTICIPATE IN SOMETHING SHARED</p><h1 data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-5" : undefined}>Your place in the pool.</h1><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-6" : undefined}>A proposed rewards model for the sites helping Zik grow.</p></div><div className={s.identity}><span className={s.avatar} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-7" : undefined}>F</span><div><strong data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-8" : undefined}>Founding affiliate</strong><small data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-9" : undefined}>Example account · no sign-in required</small></div></div></div>
      <div className={s.notice}><strong data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-10" : undefined}>Demo — illustrative data.</strong> All figures, activity and settlement statuses are fictional. Proposed commercial terms are not commitments; no real earnings or payments are shown.</div>
      <nav className={s.tabs} aria-label="Dashboard sections">{[["overview", "Overview"], ["calculation", "How it works"], ["reporting", "Reporting"], ["history", "History"], ["programme", "Programme"], ["products", "Products"]].map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav>
      <section id="overview" aria-labelledby="overview-title"><div className={s.sectionHeading}><h2 id="overview-title" data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-11" : undefined}>Overview</h2><span data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-12" : undefined}>Latest completed example window · 1–14 Sep 2026</span></div><div className={s.metrics}>
        <article className={s.feature}><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-13" : undefined}>Illustrative period allocation</p><strong>{money(latest.allocation)}</strong><small>Example share of a {money(latest.pool)} pool</small></article>
        <article className={s.metric}><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-14" : undefined}>Founding weight</p><strong data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-15" : undefined}>2×</strong><small data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-16" : undefined}>Example standard weight: 1×</small></article>
        <article className={s.metric}><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-17" : undefined}>Share of affiliate pool</p><strong>{percent(latest.share)}</strong><small data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-18" : undefined}>2 of 200 eligible weight units</small></article>
      </div></section>
      <section id="calculation" className={s.section} aria-labelledby="calculation-title"><div className={s.sectionHeading}><h2 id="calculation-title" data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-19" : undefined}>How rewards are calculated</h2><span data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-20" : undefined}>Shared pool. No purchase-by-purchase commission.</span></div><div className={s.twoCol}>
        <article className={s.card}><p className={s.eyebrow} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-21" : undefined}>01 / THE PROPOSED SPLIT</p><h3 data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-22" : undefined}>One purchase. A shared contribution.</h3><p>Example eligible Card and Pass gross revenue: <strong>{money(demoNetwork.grossRevenue)}</strong>.</p><div className={s.bar} aria-label="40% Zik and 60% participants"><span style={{ width: "40%" }} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-23" : undefined}>40% Zik</span><span style={{ width: "60%" }} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-24" : undefined}>60% participants</span></div><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-25" : undefined}>Within the 60% participant allocation: <strong>45% selling store / 55% affiliate pool.</strong></p><div className={`${s.bar} ${s.participantBar}`} aria-label="Participant allocation: 45% selling store and 55% affiliate pool"><span style={{ width: "45%" }} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-66" : undefined}>45% store</span><span style={{ width: "55%" }} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-67" : undefined}>55% pool</span></div><div className={s.split}>
          <div><i className={s.inkDot} /><strong data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-26" : undefined}>40% Zik</strong><span>{money(latest.zik)}</span><small data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-27" : undefined}>Costs, overheads and potential profit</small></div><div><i className={s.storeDot} /><strong data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-28" : undefined}>27% store</strong><span>{money(latest.store)}</span><small data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-29" : undefined}>Equivalent share of gross revenue</small></div><div><i className={s.poolDot} /><strong data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-30" : undefined}>33% pool</strong><span>{money(latest.pool)}</span><small data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-31" : undefined}>Equivalent share of gross revenue</small></div>
        </div><p className={s.note} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-32" : undefined}>Proposed rates only. Tax, settlement, refunds and online purchases without a selling store remain policy decisions.</p></article>
        <article className={s.card}><p className={s.eyebrow} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-33" : undefined}>02 / EXPLORE THE EXAMPLE</p><h3 data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-34" : undefined}>A fixed weight. A changing share.</h3><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-35" : undefined}>Each additional example affiliate adds 1 weight unit. The founding affiliate keeps its 2 units.</p>
          <label className={s.sliderLabel} htmlFor="additional">Additional affiliates <strong>{additional}</strong></label><input id="additional" type="range" min="0" max="800" step="10" value={additional} onChange={e => setAdditional(Number(e.target.value))} />
          <label className={s.sliderLabel} htmlFor="gross">Eligible gross revenue <strong>{money(gross)}</strong></label><input id="gross" type="range" min="0" max="50000" step="500" value={gross} onChange={e => setGross(Number(e.target.value))} />
          <div className={s.result} aria-live="polite" aria-atomic="true"><small>2 ÷ {200 + additional} total weight = {percent(simulation.share)} pool share</small><strong>{money(simulation.allocation)}</strong><span>Simulated allocation from a {money(simulation.pool)} pool</span></div><button type="button" className={s.button} onClick={() => { setAdditional(0); setGross(10000); }} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-36" : undefined}>Reset simulation</button><p className={s.note} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-37" : undefined}>Revenue × 33% × (affiliate weight ÷ total eligible weight). Display rounded to pennies; no settlement rounding policy is assumed.</p>
        </article>
      </div></section>
      <section id="reporting" className={s.section} aria-labelledby="reporting-title"><div className={s.sectionHeading}><h2 id="reporting-title" data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-38" : undefined}>Activity, with less detail by design.</h2><span data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-39" : undefined}>Demo aggregate reporting</span></div><div className={s.twoCol}><article className={s.card}><h3 data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-40" : undefined}>Example visitor / referral activity</h3><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-41" : undefined}>Illustrative activity counts, not unique people or attributed purchases.</p><div className={s.tableWrap} tabIndex={0} role="region" aria-label="Demo activity table; scroll horizontally if needed"><table><caption className={s.srOnly}>Demo activity across multi-day reporting windows</caption><thead><tr><th scope="col">Window</th><th scope="col">Activity</th><th scope="col">Treatment</th></tr></thead><tbody>{reportingWindows.map(row => <tr key={row.window}><th scope="row">{row.window}</th><td>{row.activity}</td><td>{row.treatment}</td></tr>)}</tbody></table></div></article><article className={`${s.card} ${s.privacy}`}><span className={s.badge} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-42" : undefined}>Aggregate by design</span><h3 data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-43" : undefined}>Participation doesn’t need a customer trail.</h3><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-44" : undefined}>Affiliate rewards do not require linking an individual Pass purchase to a visited site. The example pool is allocated by eligible weight.</p><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-45" : undefined}>Multi-day batching reduces linkability; it does not guarantee anonymity. Low-volume windows are combined or withheld. Thresholds and reporting windows still need a defined policy.</p><p className={s.note} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-46" : undefined}>No individual visitor lists, exact visit times, identities, card serials, payment references or customer journeys. This dashboard collects no activity.</p></article></div></section>
      <section id="history" className={`${s.section} ${s.card}`} aria-labelledby="history-title"><div className={s.sectionHeading}><h2 id="history-title" data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-47" : undefined}>Allocation history</h2><span data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-48" : undefined}>Examples only · no money has moved</span></div><div className={s.tableWrap} tabIndex={0} role="region" aria-label="Demo allocation history; scroll horizontally if needed"><table><caption className={s.srOnly}>Illustrative allocations and simulated settlement statuses</caption><thead><tr><th scope="col">Reporting period</th><th scope="col">Example pool</th><th scope="col">Weight / total</th><th scope="col">Example allocation</th><th scope="col">Simulated status</th></tr></thead><tbody>{allocationHistory.map(row => { const value = calculateAllocation(row.gross, 2, row.totalWeight); return <tr key={row.window}><th scope="row">{row.window}</th><td>{money(value.pool)}</td><td>2 / {row.totalWeight}</td><td><strong>{money(value.allocation)}</strong></td><td><span className={s.status}>{row.status}</span></td></tr>; })}</tbody></table></div></section>
      <section id="programme" className={s.section} aria-labelledby="programme-title"><div className={s.sectionHeading}><h2 id="programme-title" data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-49" : undefined}>Built for the long view.</h2><span data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-50" : undefined}>Programme & roadmap · proposals</span></div><div className={s.threeCol}><article className={s.card}><p className={s.eyebrow} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-51" : undefined}>FOUNDING PARTICIPATION</p><h3 data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-52" : undefined}>Your weight stays. Your share evolves.</h3><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-53" : undefined}>Founding affiliates retain an enhanced weight in the proposed model. These 2× and 1× weights are examples, not final eligibility rules or contractual guarantees.</p><ul className={s.scale}>{[200, 400, 1000].map(total => <li key={total}><span>{total} total weight</span><strong>{percent(2 / total)}</strong></li>)}</ul><small data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-54" : undefined}>Illustrative sliding-scale preview; founding weight remains 2. Future rate changes would follow published milestones; milestones are not yet defined.</small></article><article className={s.card}><span className={s.badge} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-55" : undefined}>Under consideration</span><h3 data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-56" : undefined}>Per-visitor rewards</h3><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-57" : undefined}>A possible future programme, with no rate, launch date or earnings promise. No per-visitor rewards are included in this simulation.</p></article><article className={s.card}><span className={s.badge} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-58" : undefined}>Proposal only</span><h3 data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-59" : undefined}>A broader product pool</h3><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-60" : undefined}>Other Zik products could contribute in future. No such contributions are active in this example, and the Card / Pass split does not automatically apply to them.</p></article></div></section>
      <section id="products" className={s.section} aria-labelledby="products-title"><div className={s.sectionHeading}><h2 id="products-title" data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-61" : undefined}>The Zik product family</h2><span data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-62" : undefined}>All prices provisional</span></div><div className={s.threeCol}>{demoProducts.map(product => <article className={s.card} key={product.name}><p className={s.eyebrow} data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-63" : undefined}>PROVISIONAL PRICE</p><h3>{product.name}</h3><strong className={s.price}>{product.price}</strong><p>{product.detail}</p></article>)}</div></section>
      <footer className={s.footer}><strong data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-64" : undefined}>Demo — illustrative data</strong><p data-local-edit={process.env.NODE_ENV === "development" ? "ve-da58e1ee9eec-65" : undefined}>A conversation about the proposed programme. Eligibility, milestones, tax, refunds, settlement, reporting safeguards and wider product contributions remain to be decided.</p></footer>
    </main>
  </div>;
}
