import { mkdtempSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
let directory: string;
beforeEach(() => { vi.resetModules(); directory = mkdtempSync(path.join(os.tmpdir(), "zik-onboarding-flow-")); vi.stubEnv("ZIK_RUNTIME_DATA_DIR", directory); vi.stubEnv("NODE_ENV", "test"); });
afterEach(() => { vi.unstubAllEnvs(); rmSync(directory, { recursive: true, force: true }); });
it("activates a newly onboarded client only after a real signed age-check and one-time code exchange", async () => {
  const { createRegistration, updateRegistration, getRegistration } = await import("@/lib/server/affiliate-onboarding");
  const { generateKeyPair, signString } = await import("@/lib/shared/crypto/ed25519");
  const { startEnrollment, verifyPossessionCode, advanceCoolingOff } = await import("@/lib/server/enrollment-service");
  const { completeAffiliateChallenge } = await import("@/lib/server/affiliate-verifier");
  const { POST: authorize } = await import("@/app/api/affiliate/authorize/route");
  const { POST: exchange } = await import("@/app/api/affiliate/token/route");
  const { registration: row, token } = createRegistration("New affiliate", "http://localhost:3003", "http://localhost:3003/api/zik/callback");
  const { secret } = updateRegistration(row.id, token, "credentials");
  const makeRequest = (endpoint: string, fields: object) => new NextRequest(`http://localhost/api/affiliate/${endpoint}`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${secret}` }, body: JSON.stringify({ client_id: row.id, redirect_uri: row.callback, state: "onboarding-real-roundtrip", ...fields }) });
  const response = await authorize(makeRequest("authorize", {})); expect(response.status).toBe(200); const challenge = await response.json();
  expect(getRegistration(row.id, token).connectedAt).toBeTruthy();
  expect((await exchange(makeRequest("token", { code: "invalid" }))).status).toBe(400);
  expect(getRegistration(row.id, token).verifiedAt).toBeUndefined();
  const holder = await generateKeyPair();
  const enrollment = await startEnrollment({ application: { identity_match: { first_name: "Affiliate", last_name: "Tester", date_of_birth: "1995-01-01", current_home_address: "1 Demo Street" }, bank_name: "Monzo", submitted_at: new Date().toISOString(), demo_scenario: "clean_adult_match" }, holderPublicKey: holder.publicKeyJwk, applicationFingerprint: "onboarding-integration-test" });
  await verifyPossessionCode(enrollment.id, enrollment.bank_verification.code);
  const issued = await advanceCoolingOff(enrollment.id); expect(issued.issued_credential).toBeTruthy();
  const result = await completeAffiliateChallenge({ requestId: challenge.request_id, presentationBundle: { credential: issued.issued_credential!, challenge: challenge.challenge, holder_signature: await signString(holder.privateKeyJwk, challenge.challenge), holder_algorithm: "Ed25519", presented_at: new Date().toISOString() } });
  if (result.outcome !== "approved") throw new Error("Expected an approved signed age check.");
  const redeemed = await exchange(makeRequest("token", { code: result.code })); expect(redeemed.status).toBe(200); expect(await redeemed.json()).toMatchObject({ age_over: true, threshold: 18 });
  expect(getRegistration(row.id, token).verifiedAt).toBeTruthy();
  expect(updateRegistration(row.id, token, "activate").registration.state).toBe("active");
  expect((await exchange(makeRequest("token", { code: result.code }))).status).toBe(400);
  updateRegistration(row.id, token, "disable");
  expect((await authorize(makeRequest("authorize", {}))).status).toBe(401);
});
