import { test, expect } from '@playwright/test';

test('a saved phrase restores a Vault in a fresh browser without the old phone or card', async ({ page, browser, request }) => {
  test.setTimeout(120_000);
  const reset = await request.post('/api/demo/reset');
  expect(reset.ok()).toBeTruthy();
  await page.goto('/vault');
  await page.getByRole('button', { name: 'Get Zik Vault' }).click();
  await page.getByRole('button', { name: 'Continue to payment' }).click();
  await page.getByRole('button', { name: /Pay £0.35/ }).click();
  await page.getByLabel('Legal name').fill('Recovery Test Person');
  await page.getByLabel('Delivery address').fill('A private recovery address');
  await page.getByLabel('Create a passphrase').fill('original vault passphrase');
  await page.getByLabel('Confirm passphrase').fill('original vault passphrase');
  await page.getByRole('button', { name: 'Create encrypted Vault' }).click();
  await page.getByRole('link', { name: 'Set up recovery phrase', exact: true }).click();
  await page.getByRole('button', { name: 'Set up recovery phrase', exact: true }).click();
  const words = await page.getByRole('list', { name: 'Your 24 recovery words' }).getByRole('listitem').allTextContents();
  expect(words).toHaveLength(24);
  const phrase = words.map(word => word.replace(/^\d+\.\s*/, '')).join(' ');
  const requests: string[] = [];
  page.on('request', req => { if (req.url().includes('/api/account-recovery')) requests.push(req.postData() ?? ''); });
  await page.getByRole('button', { name: 'I’ve written them down' }).click();
  await expect(page.getByRole('list', { name: 'Your 24 recovery words' })).toHaveCount(0);
  await page.getByLabel('All 24 words, in order').fill(phrase);
  await page.getByLabel('Current Vault passphrase').fill('original vault passphrase');
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Save encrypted backup' }).click();
  await expect(page.getByText('Recovery backup saved', { exact: true })).toBeVisible({ timeout: 30000 });
  expect(requests.join('')).not.toContain(phrase);
  expect(requests.join('')).not.toContain('Recovery Test Person');
  expect(requests.join('')).not.toContain('original vault passphrase');

  const fresh = await browser.newContext({ baseURL: process.env.ZIK_E2E_BASE_URL ?? 'http://localhost:3000', viewport: { width: 390, height: 844 } });
  const replacement = await fresh.newPage();
  await replacement.goto('/account-recovery/restore');
  await replacement.getByLabel('Your 24-word recovery phrase').fill(phrase);
  await replacement.getByRole('button', { name: 'Find my encrypted backup' }).click();
  await expect(replacement.getByRole('heading', { name: 'Review what will be restored' })).toBeVisible();
  await replacement.getByLabel('New Vault passphrase', { exact: true }).fill('replacement vault passphrase');
  await replacement.getByLabel('Confirm new Vault passphrase').fill('replacement vault passphrase');
  await replacement.getByRole('checkbox').check();
  await replacement.getByRole('button', { name: 'Restore on this device' }).click();
  await expect(replacement.getByText('Recovery completed on this device', { exact: true })).toBeVisible({ timeout: 30000 });
  await replacement.getByRole('link', { name: 'Open Vault', exact: true }).click();
  await replacement.getByLabel('Vault key').fill('replacement vault passphrase');
  await replacement.getByRole('button', { name: 'Unlock Vault' }).click();
  await expect(replacement.getByRole('heading', { name: 'Vault.' })).toBeVisible({ timeout: 20000 });
  await expect(replacement.getByText('Recovery Test Person', { exact: true }).first()).toBeVisible();
  await fresh.close();
});
