import { test, expect } from '@playwright/test';

test('private customer support, recovery triage and verified bug resolution', async ({ page, browser }) => {
  test.skip(!process.env.ZIK_E2E_ADMIN_PASSWORD, 'Requires an isolated server with test admin credentials.');
  const subject = `Recovery screen trouble ${Date.now()}`;
  await page.goto('/help');
  await page.getByLabel('What do you need help with?').selectOption('recovery');
  await page.getByLabel('Subject', { exact: true }).fill(subject);
  await page.getByLabel('What happened?').fill('I lost my phone and card and need help finding the recovery screen.');
  await page.getByLabel('I have removed secrets').check();
  await page.getByRole('button', { name: 'Create private help ticket' }).click();
  await expect(page).toHaveURL(/\/help\/ticket\//);
  await expect(page.getByRole('heading', { name: subject })).toBeVisible();
  const ticketUrl = page.url();
  const adminContext = await browser.newContext();
  const admin = await adminContext.newPage();
  await admin.goto('/admin');
  await admin.getByLabel('Admin username').fill(process.env.ZIK_E2E_ADMIN_USERNAME ?? 'test-owner');
  await admin.getByLabel('Admin password').fill(process.env.ZIK_E2E_ADMIN_PASSWORD!);
  await admin.getByRole('button', { name: 'Sign in', exact: true }).click();
  await admin.getByRole('button', { name: 'Recovery', exact: true }).click();
  await admin.getByLabel('Search workspace').fill(subject);
  await expect(admin.getByRole('heading', { name: subject })).toBeVisible();
  await admin.getByRole('button', { name: 'Assign to me' }).click();
  await admin.getByLabel('Recovery handling outcome').selectOption('guidance_sent');
  await admin.getByRole('button', { name: 'Save ticket details' }).click();
  await expect(admin.getByRole('status').filter({ hasText: /^Saved\.$/ })).toHaveText('Saved.');
  await admin.getByLabel('Message visibility').selectOption('internal');
  await admin.getByLabel('Internal note', { exact: true }).fill('Internal investigation detail for staff only.');
  await admin.getByRole('button', { name: 'Save internal note' }).click();
  await expect(admin.getByText('Internal investigation detail for staff only.', { exact: true })).toBeVisible();
  await admin.getByLabel('Customer reply', { exact: true }).fill('Please use the recovery screen and enter your words there only.');
  await admin.getByRole('button', { name: 'Send customer reply' }).click();
  await expect(admin.getByText('Please use the recovery screen and enter your words there only.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Check for replies' }).click();
  await expect(page.getByText('Please use the recovery screen and enter your words there only.', { exact: true })).toBeVisible();
  await expect(page.getByText('Internal investigation detail for staff only.')).toHaveCount(0);
  await admin.getByRole('button', { name: 'Link engineering issue' }).click();
  await expect(admin.getByText(`Linked engineering issue: ${subject}`)).toBeVisible();
  await admin.getByRole('button', { name: 'Bugs', exact: true }).click();
  await admin.getByLabel('Search workspace').fill(subject);
  await admin.getByLabel('Bug status').selectOption('resolved');
  await admin.getByLabel('Fix summary', { exact: true }).fill('Recovery navigation corrected in the test release.');
  await admin.getByLabel('Verification evidence / tests').fill('Verified recovery screen navigation on desktop and mobile.');
  await admin.getByRole('button', { name: 'Save bug', exact: true }).click();
  await expect(admin.getByRole('status').filter({ hasText: /^Saved\.$/ })).toHaveText('Saved.');
  await admin.screenshot({ path: '/tmp/zik-support-dashboard.png', fullPage: true });
  await admin.getByRole('button', { name: 'Recovery', exact: true }).click();
  await admin.getByLabel('Search workspace').fill(subject);
  await admin.getByRole('combobox', { name: /^Status/ }).selectOption('resolved');
  await admin.getByLabel('Resolution · Visible to the customer').fill('Recovery navigation is fixed. Please retry and reply if you still need help.');
  await admin.getByRole('button', { name: 'Save ticket details' }).click();
  await expect(admin.getByRole('status').filter({ hasText: /^Saved\.$/ })).toHaveText('Saved.');
  await page.getByRole('button', { name: 'Check for replies' }).click();
  await expect(page.getByText('Recovery navigation is fixed. Please retry and reply if you still need help.', { exact: true })).toBeVisible();
  await page.getByLabel('Reply to support').fill('I still need help with the next screen.');
  await page.getByRole('button', { name: 'Send reply', exact: true }).click();
  await expect(page.getByText('Open', { exact: true })).toBeVisible();
  const stranger = await browser.newContext();
  const strangerPage = await stranger.newPage();
  await strangerPage.goto(ticketUrl);
  await expect(strangerPage.getByRole('alert').filter({ hasText: 'A ticket reference alone' })).toContainText('A ticket reference alone cannot grant access');
  await expect(strangerPage.getByText(subject)).toHaveCount(0);
  await stranger.close();
  await adminContext.close();
});
