import { test, expect } from '@playwright/test';

const demo = { name: 'passport-copy-demo.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aG6kAAAAASUVORK5CYII=', 'base64') };
test('customer → verifier → customer → fingerprint check, including persistence and single selection', async ({ page }) => {
  await page.goto('/validate');
  await page.getByRole('button', { name: 'Upload document', exact: true }).click();
  await page.getByLabel('Document upload').setInputFiles(demo);
  await page.getByRole('button', { name: 'Continue →', exact: true }).click();
  await page.getByRole('combobox', { name: 'Receiving organisation', exact: true }).selectOption('northstar');
  await page.getByRole('combobox', { name: 'Document type', exact: true }).selectOption('passport-copy');
  await page.getByRole('combobox', { name: 'Jurisdiction', exact: true }).selectOption('GB-EAW');
  await page.getByRole('radio', { name: 'Certified copy', exact: true }).check();
  await page.getByRole('radio', { name: 'Not sure', exact: true }).check();
  await expect(page.getByRole('radio', { name: 'Certified copy', exact: true })).not.toBeChecked();
  await page.getByRole('button', { name: 'Continue →', exact: true }).click();
  await expect(page.getByText('Simulated analysis:')).toBeVisible();
  await page.getByRole('button', { name: 'Continue →', exact: true }).click();
  await page.getByRole('radio', { name: /Dr Maya Evans/ }).check();
  await page.getByRole('radio', { name: /Alex Morgan/ }).check();
  await expect(page.getByRole('radio', { name: /Dr Maya Evans/ })).not.toBeChecked();
  await page.getByRole('button', { name: 'Continue with selected verifier' }).click();
  await expect(page.getByText('Awaiting verifier', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText('passport-copy-demo.png', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Switch to verifier view' }).click();
  await expect(page.getByRole('button', { name: 'Validate', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Review document', exact: true }).click();
  await expect(page.getByAltText('Uploaded document preview')).toBeVisible();
  await page.getByRole('button', { name: 'Validate', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Validate document', exact: true })).toBeDisabled();
  await page.getByRole('checkbox', { name: 'I have completed the checks described above.' }).check();
  await expect(page.getByRole('button', { name: 'Validate document', exact: true })).toBeDisabled();
  for (const checkbox of await page.getByRole('group', { name: 'Required evidence checks' }).getByRole('checkbox').all()) await checkbox.check();
  await page.getByRole('button', { name: 'Validate document', exact: true }).click();
  await expect(page.getByRole('heading', { name: '✓ ZIK VALIDATED' })).toBeVisible();
  await page.getByRole('button', { name: 'Return to customer' }).click();
  await page.getByRole('link', { name: 'View validation', exact: true }).click();
  await page.getByRole('button', { name: 'Check validation' }).click();
  await expect(page.getByRole('heading', { name: 'Validation confirmed ✓' })).toBeVisible();
  await expect(page.getByText('Document not compared yet.')).toBeVisible();
  await page.getByLabel('Compare document').setInputFiles(demo);
  await expect(page.getByText('Document unchanged · Fingerprint matches ✓')).toBeVisible();
  await page.getByLabel('Compare document').setInputFiles({ ...demo, buffer: Buffer.from('different document') });
  await expect(page.getByText('Document differs · Fingerprint does not match')).toBeVisible();
});

test('mobile eligibility, declined request and unknown validation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/validate');
  await page.getByRole('button', { name: 'Upload document', exact: true }).click();
  await page.getByLabel('Document upload').setInputFiles({ name: 'unsupported.txt', mimeType: 'text/plain', buffer: Buffer.from('dummy') });
  await expect(page.getByRole('alert').filter({ hasText: 'Choose a non-empty PDF' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Continue →' })).toBeDisabled();
  await page.getByLabel('Document upload').setInputFiles(demo);
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('combobox', { name: 'Receiving organisation', exact: true }).selectOption('northstar');
  await page.getByRole('combobox', { name: 'Document type', exact: true }).selectOption('consent-form');
  await page.getByRole('combobox', { name: 'Jurisdiction', exact: true }).selectOption('GB-EAW');
  await page.getByRole('radio', { name: 'Witness a signature', exact: true }).check();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await expect(page.getByText('I witnessed the person presented sign this document.')).toBeVisible();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await expect(page.getByRole('radio', { name: /Dr Maya Evans/ })).toBeDisabled();
  await page.getByRole('radio', { name: /Elena Rossi/ }).check();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/zik-validate-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Continue with selected verifier' }).click();
  await page.getByRole('button', { name: 'Switch to verifier view' }).click();
  await page.getByRole('button', { name: 'Cannot validate', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Confirm decline' })).toBeDisabled();
  await page.getByLabel('Reason for declining').selectOption('evidence-missing');
  await page.getByRole('button', { name: 'Confirm decline' }).click();
  await page.getByRole('button', { name: 'Return to customer' }).click();
  await expect(page.getByText('Declined', { exact: true }).last()).toBeVisible();
  await expect(page.getByText('Required evidence or original document is unavailable', { exact: true })).toBeVisible();
  await page.goto('/validate/verify');
  await page.getByRole('textbox', { name: 'Zik Validation ID' }).fill('ZV-UNKNOWN');
  await page.getByRole('button', { name: 'Check validation' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'No completed validation found' })).toBeVisible();
});

test('recipient policy narrows matches, blocks unsupported context and survives reload', async ({ page }) => {
  await page.goto('/validate');
  await page.getByRole('button', { name: 'Upload document', exact: true }).click();
  await page.getByLabel('Document upload').setInputFiles(demo);
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('radio', { name: 'Not sure', exact: true }).check();
  await expect(page.getByRole('button', { name: 'Continue →' })).toBeDisabled();
  await page.getByRole('combobox', { name: 'Receiving organisation', exact: true }).selectOption('harbour');
  await page.getByRole('combobox', { name: 'Document type', exact: true }).selectOption('passport-copy');
  await page.getByRole('combobox', { name: 'Jurisdiction', exact: true }).selectOption('GB-SCT');
  await page.getByRole('button', { name: 'Continue →' }).click();
  await expect(page.getByRole('heading', { name: 'Requirements need clarification' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Continue →' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('combobox', { name: 'Jurisdiction', exact: true }).selectOption('GB-EAW');
  await page.getByRole('button', { name: 'Continue →' }).click();
  await expect(page.getByText(/harbour-passport-eaw · Version 2/)).toBeVisible();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await expect(page.getByRole('radio', { name: /Alex Morgan/ })).toBeDisabled();
  await expect(page.getByRole('radio', { name: /Dr Maya Evans/ })).toBeDisabled();
  await page.getByRole('radio', { name: /Elena Rossi/ }).check();
  // Changing requirement context must discard the prior single-select verifier.
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('combobox', { name: 'Receiving organisation', exact: true }).selectOption('northstar');
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await expect(page.getByRole('radio', { name: /Elena Rossi/ })).not.toBeChecked();
  await expect(page.getByRole('button', { name: 'Continue with selected verifier' })).toBeDisabled();
  await page.getByRole('radio', { name: /Dr Maya Evans/ }).check();
  await page.getByRole('button', { name: 'Continue with selected verifier' }).click();
  await expect(page.getByText('Awaiting verifier', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText('northstar-passport-eaw · Version 2 · Fictional policy')).toBeVisible();
  await expect(page.getByText('Northstar College — fictional', { exact: true })).toBeVisible();
});

test('clarification is separate from an in-person witnessing appointment', async ({ page }) => {
  await page.goto('/validate');
  await page.getByRole('button', { name: 'Upload document', exact: true }).click();
  await page.getByLabel('Document upload').setInputFiles(demo);
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('combobox', { name: 'Receiving organisation', exact: true }).selectOption('northstar');
  await page.getByRole('combobox', { name: 'Document type', exact: true }).selectOption('consent-form');
  await page.getByRole('combobox', { name: 'Jurisdiction', exact: true }).selectOption('GB-EAW');
  await page.getByRole('radio', { name: 'Certified copy', exact: true }).check();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await expect(page.getByRole('heading', { name: 'Requirements need clarification' })).toBeVisible();
  await expect(page.getByText(/requirements are unresolved, not that you need an in-person visit/)).toBeVisible();
  await page.getByRole('button', { name: 'Use witness a signature' }).click();
  await expect(page.getByRole('heading', { name: 'In-person witnessing appointment' })).toBeVisible();
  await expect(page.getByText(/Do not sign before the appointment/)).toBeVisible();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('radio', { name: /Alex Morgan/ }).check();
  await page.getByRole('button', { name: 'Continue with selected verifier' }).click();
  await page.getByRole('button', { name: 'Switch to verifier view' }).click();
  await page.getByRole('button', { name: 'Review document', exact: true }).click();
  await page.getByRole('button', { name: 'Validate', exact: true }).click();
  const appointment = page.getByRole('checkbox', { name: /I attended the in-person appointment/ });
  for (const checkbox of await page.getByRole('checkbox').all()) {
    if (!(await checkbox.getAttribute('type') === 'checkbox')) continue;
    if (await checkbox.evaluate(el => el.parentElement?.textContent?.includes('I attended the in-person appointment'))) continue;
    await checkbox.check();
  }
  await expect(page.getByRole('button', { name: 'Validate document', exact: true })).toBeDisabled();
  await appointment.check();
  await page.getByRole('button', { name: 'Validate document', exact: true }).click();
  await page.getByRole('button', { name: 'Return to customer' }).click();
  await expect(page.getByText('In-person checks confirmed · Simulated', { exact: true })).toBeVisible();
});
