export const SUPPORT_POLICY_VERSION = '2026-09-20';
export const SUPPORT_PLAYBOOK = [
  { title: '1. Triage and acknowledge', body: 'Read the customer’s description, confirm the affected product and impact, and assign an owner. Ask for a time, browser/device, safe reproduction steps and an error reference. Check for duplicates and current incidents before requesting more information.' },
  { title: '2. Protect customer data', body: 'Never request seed phrases, Vault or messaging passphrases, PINs, private keys, identity-document images or payment-card details. Support messages can be read by the support team; they are not a private Vault. Ask customers to redact screenshots and logs. This help desk accepts text only.' },
  { title: '3. Troubleshoot without destroying data', body: 'Check connectivity and service availability, retry once, then use the smallest reversible step. Do not advise clearing browser data, reinstalling or deleting a Vault until a recoverable backup is confirmed and the customer understands what may be lost. Record steps attempted and their results.' },
  { title: '4. Handle phone and card loss', body: 'Direct the customer to /account-recovery/restore on their own replacement device. They enter their phrase there, never in a ticket. A ticket, email address or identity story is not proof of account control. Admins cannot view/decrypt backups, retrieve phrases or bypass recovery keys. With no phrase or usable backup, explain the limits and arrange a fresh in-person verification through the normal flow; never claim the old Vault can be recovered.' },
  { title: '5. Escalate bugs and incidents', body: 'Link related tickets and error references to one bug. Record reproduction steps, expected/actual behavior and the environment. Treat suspected account compromise, security/privacy exposure or widespread data loss as urgent. Investigate and contain through authorized operational channels; never paste secrets into bug records or execute customer-supplied code.' },
  { title: '6. Verify a fix and close the loop', body: 'A resolved bug requires a fix summary and verification evidence, with a change/release link when available. A resolved or closed ticket requires a customer-visible resolution. Tell the customer what changed, any remaining limits and what to try next. A customer reply reopens a resolved ticket; closing does not erase its history.' },
  { title: '7. Review targets and retention', body: 'Priorities have internal first-response targets: urgent 4 hours, high 24 hours, normal 72 hours and low 120 hours, measured as calendar hours. These are operating targets, not a promised service level. Review overdue and unassigned requests each working day. Apply retention regularly: closed ticket contents and access keys after 90 days; audit metadata after 180 days. Keep personal data out of engineering records.' },
] as const;
export const REPLY_TEMPLATES = [
  { title: 'Ask for safe diagnostics', body: 'Thanks for reporting this. Please share the affected screen, approximately when it happened, your browser/device, the steps you took and any error reference shown. Do not include your recovery words, passphrases, PIN, identity documents or payment details. Please keep your browser data and Vault intact while we investigate.' },
  { title: 'Lost phone and card', body: 'If you saved your 24-word recovery phrase and enabled an encrypted backup, open /account-recovery/restore on your own replacement device. Enter the words only on that recovery screen, never here. We cannot retrieve your phrase or bypass it. If you no longer have a phrase or usable backup, tell us that without sending any secrets so we can explain the fresh-verification options.' },
  { title: 'Engineering investigation', body: 'We have linked your report to an engineering investigation. We will post updates in this private ticket. Please do not clear your browser storage or delete your Vault while we investigate. If the issue changes, reply with the new symptoms and a time.' },
  { title: 'Verify a fix', body: 'We have made a fix for the issue described. Please retry the original steps without deleting your saved data. Let us know whether it now works, and include any new error reference if it does not. Replying here will reopen the ticket if further help is needed.' },
] as const;
