import { CustomerShell } from '@/components/customer/customer-shell';
import { ButtonLink, Card } from '@/components/customer/ui';
import { SUPPORT_POLICY_VERSION } from '@/lib/shared/support/policy';
export const metadata = { title: 'Support policy · Zik' };
export default function SupportPolicyPage() {
  return <CustomerShell active="help" title="Support policy"><div className="space-y-5 py-5"><p className="text-xs font-bold uppercase tracking-widest text-[var(--zk-text-soft)]">Updated {SUPPORT_POLICY_VERSION}</p><h1 className="text-3xl font-extrabold" data-local-edit={process.env.NODE_ENV === "development" ? "ve-80a562e89736-1" : undefined}>Help you can use safely.</h1>
    <Card className="space-y-3 !rounded-2xl p-5"><h2 className="text-xl font-bold" data-local-edit={process.env.NODE_ENV === "development" ? "ve-80a562e89736-2" : undefined}>What support can do</h2><p className="text-sm leading-relaxed" data-local-edit={process.env.NODE_ENV === "development" ? "ve-80a562e89736-3" : undefined}>We can help troubleshoot, explain recovery options, investigate bug reports and keep you informed through your private ticket. We prioritise suspected security/privacy issues, data loss and account access problems. We do not currently promise a response time or offer an emergency service.</p></Card>
    <Card className="space-y-3 !rounded-2xl p-5"><h2 className="text-xl font-bold" data-local-edit={process.env.NODE_ENV === "development" ? "ve-80a562e89736-4" : undefined}>Keep your recovery words private</h2><p className="text-sm leading-relaxed" data-local-edit={process.env.NODE_ENV === "development" ? "ve-80a562e89736-5" : undefined}>Support will never ask for your 24-word recovery phrase, Vault or messaging passphrase, PIN, private keys, ID images or full payment details. Your recovery phrase is entered only on the recovery screen on your own device. We cannot retrieve it, decrypt your backup, or restore documents that were never backed up.</p><ButtonLink href="/account-recovery/restore" variant="secondary">Lost your phone and card?</ButtonLink></Card>
    <Card className="space-y-3 !rounded-2xl p-5"><h2 className="text-xl font-bold" data-local-edit={process.env.NODE_ENV === "development" ? "ve-80a562e89736-6" : undefined}>Before deleting anything</h2><p className="text-sm leading-relaxed" data-local-edit={process.env.NODE_ENV === "development" ? "ve-80a562e89736-7" : undefined}>Keep your browser storage and Vault intact while troubleshooting. Clearing site data or reinstalling can destroy your only local copy. First check that you have the correct recovery phrase and a saved, recoverable backup. Tell us what you tried and include an error reference if one is shown.</p></Card>
    <Card className="space-y-3 !rounded-2xl p-5"><h2 className="text-xl font-bold" data-local-edit={process.env.NODE_ENV === "development" ? "ve-80a562e89736-8" : undefined}>Your ticket and replies</h2><p className="text-sm leading-relaxed" data-local-edit={process.env.NODE_ENV === "development" ? "ve-80a562e89736-9" : undefined}>Support tickets are readable by the support team; they do not use Vault encryption. We store your message, optional contact email, any diagnostics you choose to share, and the conversation history. Text only; attachments are not accepted. Replies appear in your private ticket, not by automatic email. Save its private link: anyone with the link can access the conversation. A contact email is not verified proof of ownership.</p><p className="text-sm leading-relaxed" data-local-edit={process.env.NODE_ENV === "development" ? "ve-80a562e89736-10" : undefined}>Reply if you still need help, even after a ticket is resolved or closed. This reopens it. Closed ticket contents and access keys become eligible for deletion after 90 days; limited audit metadata is kept for up to 180 days when retention is applied. Tell us in your ticket if you need help with your data.</p></Card>
    <ButtonLink href="/help">Contact support</ButtonLink>
  </div></CustomerShell>;
}
